export enum Skills {
    ProficiencyInBraille = 'Proficiency in Braille',
    AttentionToDetail = 'Attention to Detail',
    KeyboardingSkills = 'Keyboarding Skills',
    KnowledgeOfAccessibilityStandards = 'Knowledge of Accessibility Standards',
    CommunicationSkills = 'Communication Skills',
    AdaptiveTechnologyProficiency = 'Adaptive Technology Proficiency',
    ProficiencyInSignLanguage = 'Proficiency in Sign Language',
    Creativity = 'Creativity',
    OrganizationalSkills = 'Organizational Skills',
    KnowledgeOfVisualStorytellingTechniques = 'Knowledge of Visual Storytelling Techniques',
    ProficiencyInSpeechRecognitionSoftware = 'Proficiency in Speech Recognition Software',
    ProblemSolvingSkills = 'Problem Solving Skills',
    TeamManagementSkills = 'Team Management Skills',
    ExpertiseInAccessibilitySoftware = 'Expertise in Accessibility Software',
    FamiliarWithSensoryAwareCounselingTechniques = 'Familiar with Sensory-aware Counseling Techniques',
    TechSavviness = 'Tech Savviness',
    Flexibility = 'Flexibility',
    Adaptability = 'Adaptability',
    AccessibilityKnowledge = 'Accessibility Knowledge',
    TechnicalProficiency = 'Technical Proficiency',
    ContinuousLearningSkills = 'Continuous Learning Skills',
    TechLiteracy = 'Tech Literacy',
    VisualDesignSkills = 'Visual Design Skills',
    StrategicThinkingSkills = 'Strategic Thinking Skills',
    TeamCollaborationSkills = 'Team Collaboration Skills',
    AnalyticalSkills = 'Analytical Skills',
    CustomerCareSkills = 'Customer Care Skills',
    CriticalThinking = 'Critical Thinking',
    AccessibilityAwareness = 'Accessibility Awareness',
    ExcellentCommunicationAndInterpersonalSkills = 'Excellent Communication and Interpersonal Skills',
    KnowledgeOfCompanyPoliciesAndProcedures = 'Knowledge of Company Policies and Procedures',
    IndustryExpertise = 'Industry Expertise',
    NetworkingAbilities = 'Networking Abilities',
    TimeManagementSkills = 'Time Management Skills'
}

export enum JobTitles {
    BrailleTranscriptionist = 'Braille Transcriptionist',
    CustomerServiceRepresentative = 'Customer Service Representative',
    BlindnessRehabilitationSpecialist = 'Blindness Rehabilitation Specialist',
    Educator = 'Educator',
    GraphicDesigner = 'Graphic Designer',
    AdministrativeAssistant = 'Administrative Assistant',
    ContentCreator = 'Content Creator',
    DataEntrySpecialist = 'Data Entry Specialist',
    Transcriptionist = 'Transcriptionist',
    LifeSkillsTrainer = 'Life Skills Trainer',
    AssistiveTechnologySpecialist = 'Assistive Technology Specialist',
    RehabilitationCounselor = 'Rehabilitation Counselor',
    VirtualAssistant = 'Virtual Assistant',
    Copywriter = 'Copywriter',
    AccessibilityConsultant = 'Accessibility Consultant',
    OnlineTutor = 'Online Tutor',
    TelecommutingSoftwareEngineer = 'Telecommuting Software Engineer',
    SocialMediaManager = 'Social Media Manager',
    MarketingCoordinator = 'Marketing Coordinator',
    OfficeAssistant = 'Office Assistant',
    LibraryAssistant = 'Library Assistant',
    FoodServiceWorker = 'Food Service Worker',
    WebDesigner = 'Web Designer',
    FreelanceWriter = 'Freelance Writer',
    EducationalAssistant = 'Educational Assistant',
    HumanResourcesAssistant = 'Human Resources Assistant',
    Consultant = 'Consultant'
}

export enum Cities {
    NewYork = "New York",
    LosAngeles = "Los Angeles",
    Chicago = "Chicago",
    Houston = "Houston",
    Boston = "Boston",
    Philadelphia = "Philadelphia"
}

export enum AccommodationFacilities {
    ScreenReadingSoftware = 'Screen reading software',
    MagnificationTools = 'Magnification tools',
    AudioNavigationGuides = 'Audio Navigation Guides',
    BrailleDisplay = 'Braille Display',
    TactileMarkings = 'Tactile Markings',
    AssistiveListeningDevices = 'Assistive Listening Devices',
    CaptioningSoftware = 'Captioning Software',
    AccessibleCommunicationTools = 'Accessible Communication Tools',
    SignLanguageInterpreters = 'Sign Language Interpreters',
    VisualCuesAndGraphicalRepresentationSoftware = 'Visual Cues and Graphical Representation Software',
    VisualCommunicationAids = 'Visual Communication Aids',
    SpeechGeneratingDevices = 'Speech Generating Devices',
    TextToSpeechSoftware = 'Text-to-Speech Software',
    CommunicationApplications = 'Communication Applications',
    AssistiveTechnologyDevices = 'Assistive Technology Devices',
    TactileGraphicsSoftware = 'Tactile Graphics Software',
    RemoteCollaborationTools = 'Remote Collaboration Tools',
    ErgonomicWorkspaceSetup = 'Ergonomic Workspace Setup',
    CollaborativeProjectManagementTools = 'Collaborative Project Management Tools',
    AccessibleCommunicationPlatforms = 'Accessible Communication Platforms',
    VisualCuesForOrientation = 'Visual Cues for Orientation',
    AccessibleSoftwareDevelopmentTools = 'Accessible Software Development Tools',
    AccessibleTransportationFacilities = 'Accessible Transportation Facilities',
    FlexibleAttendancePolicies = 'Flexible Attendance Policies',
    ErgonomicWorkstationSetup = 'Ergonomic Workstation Setup',
    VoiceControlledTechnologyDevices = 'Voice-controlled Technology Devices',
    AssistiveAids = 'Assistive Aids',
    FlexibleWorkArrangements = 'Flexible Work Arrangements',
    VoiceControlledProjectManagementTools = 'Voice-controlled Project Management Tools',
    SupportiveWorkstationsAndEquipment = 'Supportive Workstations and Equipment',
    VirtualAssistiveDevices = 'Virtual Assistive Devices',
    IndividualizedSupportPlans = 'Individualized Support Plans',
    WheelchairAccessibleWorkspace = 'Wheelchair Accessible Workspace',
    CustomizedWorkArrangements = 'Customized Work Arrangements',
    SupportiveNetworksAndCommunities = 'Supportive Networks and Communities',
    CollaborativeTaskManagementTools = 'Collaborative Task Management Tools',
    ErgonomicKeyboards = 'Ergonomic Keyboards',
    RestAreasAndQuietWorkspaces = 'Rest Areas and Quiet Workspaces',
    TelecommutingFacilities = 'Telecommuting Facilities',
    IndividualizedAccommodativeFacilities = 'Individualized Accommodative Facilities'
}
